### ISSUE TITLE
Java metrics examples should use AutoConfiguredOpenTelemetrySdk

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-examples#155]
Right now the examples just use the `GlobalOpenTelemetry` instance, which might be noop unless a system property is set. To keep things simple, we might want to just use the `AutoConfiguredOpenTelemetrySdk` instead. This is probably what most users want anyway.

**Comment by jaydeluca** [comment]
It looks like this issue was resolved by #189
