### ISSUE TITLE
Renovate is not updating spring-native `mavenBom` dependency

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-examples#210]
https://github.com/open-telemetry/opentelemetry-java-examples/blob/cf0bda5c11d2fa32b13a76b2629414fcd7fdb794/spring-native/build.gradle#L14

It looks like this is a known issue with Renovate: https://github.com/renovatebot/renovate/issues/4614

cc @jeanbisutti

**Comment by AlexCzar** [comment]
My PR removes this annoyance.
