### ISSUE TITLE
Migrate build from gradle to kotlin

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-examples#222]
The other java repos all prefer .kts for build scripts. Let's get this one off of groovy and over to kotlin for consistency.

**Comment by trask** [comment]
I don't fully recall, but this may have been intentional for the examples under the assumption that more people use gradle groovy over gradle kotlin. Probably gradle kotlin usage has only grown since then.

**Comment by mateuszrzeszutek** [comment]
> I don't fully recall, but this may have been intentional for the examples under the assumption that more people use gradle groovy over gradle kotlin. Probably gradle kotlin usage has only grown since then.

Even if that is the case, I've always thought we should advocate for using gradle kotlin, as it's the safer option with better IDE support. I'd be in favor of using kotlin even if somehow groovy turns out to be the more popular option.

**Comment by AlexCzar** [comment]
Hello, I would like to work on this.

**Comment by mateuszrzeszutek** [comment]
Thanks @AlexCzar ! I'll assign this issue to you then
