### ISSUE TITLE
only custom logger appender on collector

### ISSUE THREAD

**Issue by mosinnik** [open-telemetry/opentelemetry-java-examples#240]
In log-appender example after running Application I found only custom appender logs in collectors logs.
Log4j, logback and also JUL logs lost.

Looks like lost setup of OpenTelemetryAppender because all work fine after adding follow code after `initializeOpenTelemetry();` (https://github.com/open-telemetry/opentelemetry-java-examples/blob/main/log-appender/src/main/java/io/opentelemetry/example/logappender/Application.java#L35)
```
    io.opentelemetry.instrumentation.log4j.appender.v2_17.OpenTelemetryAppender.install(GlobalOpenTelemetry.get());
    io.opentelemetry.instrumentation.logback.appender.v1_0.OpenTelemetryAppender.install(GlobalOpenTelemetry.get());
```

**Comment by trask** [comment]
hi @mosinnik! yes, this example should be fixed, the underlying logging instrumentation changed a few months ago and no longer uses the GlobalOpenTelemetry, and requires an explicit `.install()`

**Comment by jaydeluca** [comment]
this was fixed by #282 

You can now see all the logs in the collector:

Example:

```
2024-09-22T10:18:47.928Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "debug", "resource logs": 1, "log records": 13}
2024-09-22T10:18:47.928Z        info    ResourceLog #0
Resource SchemaURL: 
Resource attributes:
     -> service.name: Str(log4j-example)
     -> telemetry.sdk.language: Str(java)
     -> telemetry.sdk.name: Str(opentelemetry)
     -> telemetry.sdk.version: Str(1.42.1)
ScopeLogs #0
ScopeLogs SchemaURL: 
InstrumentationScope log4j-logger 
LogRecord #0
ObservedTimestamp: 2024-09-22 10:18:47.727881 +0000 UTC
Timestamp: 2024-09-22 10:18:47.721882 +0000 UTC
SeverityText: INFO
SeverityNumber: Info(9)
Body: Str(A log4j log message without a span)
Attributes:
     -> thread.id: Int(1)
     -> thread.name: Str(main)
```

**Comment by jaydeluca** [comment]
@QuinnBast apologies for any confusion. I closed this issue because what was reported - appenders not being correctly installed to send messages to the collector in the documented examples - has been addressed and is working now. 

I could be mistaken but I don't think your comment is talking about the same thing? If that is the case, would you mind opening up a new issue detailing your problem?

**Comment by QuinnBast** [comment]
You might be right. I don't think my issue is specifically about the `java-examples` repo, I think this is an issue for the java OpenTelemetry client itself, but I'm not really sure where that repo is to open an issue on it?

**Comment by trask** [comment]
hi @QuinnBast, this is probably the component you're using? https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/log4j/log4j-appender-2.17/library

if so you can open issue in that repo, thanks
