### ISSUE TITLE
OTEL_EXPORTER_OTLP_HEADERS is not support by opentelemetry-spring-boot-starter

### ISSUE THREAD

**Issue by brunorabaca** [open-telemetry/opentelemetry-java-examples#300]
Hello,

OTEL_EXPORTER_OTLP_HEADERS is not support by 
`opentelemetry-spring-boot-starter 1.32.0-alpha`

I've tryed with environment variable 
`OTEL_EXPORTER_OTLP_HEADERS=api-key=xxx `
and vm option 
`-Dotel.exporter.otlp.headers=api-key=xxx`

With both got this error:
`Failed to export metrics. Server responded with gRPC status code 16. Error message:`

Dependencyes
`
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.opentelemetry</groupId>
                <artifactId>opentelemetry-bom</artifactId>
                <version>1.34.0</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>io.opentelemetry.instrumentation</groupId>
                <artifactId>opentelemetry-instrumentation-bom-alpha</artifactId>
                <version>1.32.0-alpha</version>
                <type>pom</type>
            </dependency>
        </dependencies>
</dependencyManagement>
<dependencies>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-spring-boot-starter</artifactId>
        </dependency>
</dependencies>
`

**Comment by jeanbisutti** [comment]
@brunorabaca This feature should be supported from the  next OTel Java instrumentation release (https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9950), thanks to @zeitlinger. Did you plan to create or update an example in this example repo or just wanted to report a missing/not working feature?

**Comment by brunorabaca** [comment]
@jeanbisutti Thanks for the reply.
Just to report a missing feature.
Any ETA for the new release?

**Comment by trask** [comment]
> Any ETA for the new release?

hopefully by end of this week

**Comment by brunorabaca** [comment]
@jeanbisutti @trask 
Thanks for all the help!
