### ISSUE TITLE
Need example of how to build a histogram with exponential bucket boundaries

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-examples#319]
This came up in slack. There are currently no examples here of how to create a histogram with exponential bucket boundaries. A user reading the [example for Histogram](https://github.com/open-telemetry/opentelemetry-java-examples/blob/main/metrics/src/main/java/io/opentelemetry/example/metrics/HistogramExample.java) today might believe that it's simply missing from the implementation.

As a result, I think it probably makes sense to add an example for exponential buckets to the existing example. That way, it's pretty easily findable (just like the custom bucket example is findable).

**Comment by jaydeluca** [comment]
I took a stab at this  (#396 ) 

I assume the approach I took will be a more useful example than just demonstrating the use of the system property/env var `otel.exporter.otlp.metrics.default.histogram.aggregation` and `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION`,  to enable it, but let me know if you had something else in mind.
