### ISSUE TITLE
java.lang.NoClassDefFoundError: io/opentelemetry/context/ImplicitContextKeyed exception when following the OTLP Java example.

### ISSUE THREAD

**Issue by Micah-Gafford** [open-telemetry/opentelemetry-java-examples#360]
I am trying to follow the otlp Java example [here](https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/otlp). When attempting to run the jar produced by the gradle build I am encountering the following error:

```
Error: Unable to initialize main class com.example.exporter.OtlpExporterExample
Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/context/ImplicitContextKeyed
```

I have tried to run with the dependencies listed in the example `gradle.build.kts` file along with a few other dependencies to try to fix the error but have had no luck. Does anyone know if there are dependencies or build requirements that aren't listed in the example that I should add in my `gradle.build.kts` file?

Here is my `gradle.build.kts` for reference:

```
plugins {
    java
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

description = "OpenTelemetry Example for OTLP Exporters"
val moduleName by extra { "io.opentelemetry.examples.otlp" }

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

dependencies {
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.guava)

    implementation(platform("io.opentelemetry:opentelemetry-bom:1.36.0"));
    implementation("io.opentelemetry:opentelemetry-api")
    implementation("io.opentelemetry:opentelemetry-sdk")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp")
    implementation("io.opentelemetry:opentelemetry-context")
    implementation("io.opentelemetry:opentelemetry-sdk-common")
    implementation("io.opentelemetry.semconv:opentelemetry-semconv:1.23.1-alpha")
}

application {
    // Define the main class for the application.
    mainClass = "com.example.exporter.OtlpExporterExample"
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "com.example.exporter.OtlpExporterExample"
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

```

**Comment by jkwatson** [comment]
what does your classpath look like when you try to run the jar? The gradle build doesn't bundle all the dependencies into the jar that is built, so you'll need to make sure they are on your classpath.

how are you running the jar?

**Comment by jkwatson** [comment]
You will need to include all of the dependencies, including any transitive dependencies in your classpath, otherwise, the classes that are needed will not be found.

**Comment by jkwatson** [comment]
Does `./gradlew run` work?

**Comment by jkwatson** [comment]
Check out this pull request where I add the application plugin. With that PR in place, all you have to do is...

```
cd otlp
../gradlew run
```
(after starting up the docker-compose setup in the docker directory)

**Comment by jayb1976** [comment]
@jkwatson Thank you! 

I did get the project to run. However, first I had to remove 

` ":opentelemetry-examples-spring-native",` from settings.gradle.tks as that caused a build failure. 

If you address that or mention something in the readme, I think this issue is resolved.   Thank you again!

**Comment by jkwatson** [comment]
> I did get the project to run. However, first I had to remove
> 
> ` ":opentelemetry-examples-spring-native",` from settings.gradle.tks as that caused a build failure.

Not sure what you're referring to there. Can you point me to the location on github?

**Comment by jkwatson** [comment]
> > I did get the project to run. However, first I had to remove
> > ` ":opentelemetry-examples-spring-native",` from settings.gradle.tks as that caused a build failure.
> 
> Not sure what you're referring to there. Can you point me to the location on github?

oh, in the root of the project? No idea why that would cause any failure for you. It worked fine for me as-is. Let's not confound the two issues. If you have another issue, open that as a separate one.

**Comment by jkwatson** [comment]
Please create a separate issue for that, as it doesn't have anything to do with the running of the otlp example in particular.
